version: "3"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  rabbitmq:
    image: rabbitmq:3-management-alpine

  conejos:
    build:
      context: .
      dockerfile: ./Dockerfile # Specify the Dockerfile for the uploader service
    ports:
      - "3000:3000"
      - "3001:3001"
      - "80:4200"
    depends_on:
      - postgres
      - rabbitmq
